services:
  - type: web
    name: moira-lee-live
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"

  - type: cron
    name: moira-lee-trigger
    env: python
    schedule: "*/15 * * * *"
    buildCommand: "pip install -r requirements.txt"
    command: "python generate.py"




