services:
  - type: web
    name: moira-lee
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false

cronjobs:
  - name: moira-lee-auto-update
    schedule: "*/15 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python generate.py"

