services:
  - type: web
    name: moira_lee_dialogue_live
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: starter
    branch: main
    repo: https://github.com/davidhunt-thirdgaze/moira_lee_dialogue.git

  - type: cron
    name: moira_cron_trigger
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "0 */2 * * *"  # every 2 hours
    command: python generate.py
    plan: starter
    branch: main
    repo: https://github.com/davidhunt-thirdgaze/moira_lee_dialogue.git


